# Generated by Django 3.2.12 on 2022-04-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(blank=True, max_length=500, null=True, verbose_name='positions')),
                ('image', models.ImageField(upload_to='administration', verbose_name='image')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('reseption_of_sitizens', models.CharField(blank=True, max_length=100, null=True, verbose_name='reseption_of_sitizens')),
                ('functional_duties', models.TextField(verbose_name='functional_duties')),
                ('biography', models.TextField(verbose_name='biography')),
            ],
            options={
                'verbose_name': 'administration',
                'verbose_name_plural': 'administrations',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('text3', models.TextField(verbose_name='text3')),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
            },
        ),
        migrations.CreateModel(
            name='CentralOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.CharField(blank=True, max_length=500, null=True, verbose_name='positions')),
                ('image', models.ImageField(upload_to='administration', verbose_name='image')),
                ('fullname', models.CharField(max_length=100, verbose_name='fullname')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('departament', models.CharField(blank=True, max_length=100, null=True, verbose_name='departament')),
            ],
            options={
                'verbose_name': 'centraloffice',
                'verbose_name_plural': 'centraloffices',
            },
        ),
        migrations.CreateModel(
            name='FightAgainstCorruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('text3', models.TextField(verbose_name='text3')),
                ('text4', models.TextField(verbose_name='text4')),
            ],
            options={
                'verbose_name': 'fightagainstcorruption',
                'verbose_name_plural': 'fightagainstcorruptions',
            },
        ),
        migrations.CreateModel(
            name='Ifsatasr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='fax')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'ifsatasr',
                'verbose_name_plural': 'ifsatasrs',
            },
        ),
        migrations.CreateModel(
            name='InternationalPartnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorandums', models.TextField(verbose_name='memorandums')),
                ('news', models.TextField(verbose_name='news')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'internationalpartnership',
                'verbose_name_plural': 'internationalpartnerships',
            },
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='overview', verbose_name='image')),
                ('fullname', models.CharField(blank=True, max_length=500, null=True, verbose_name='fullanem')),
                ('abbreviated_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='abreviated_name')),
                ('main_functions', models.TextField(verbose_name='main_functions')),
                ('legal_basis', models.TextField(verbose_name='legal_basis')),
                ('main_goals', models.TextField(verbose_name='main_goals')),
                ('priority_areas', models.TextField(verbose_name='priority_areas')),
            ],
            options={
                'verbose_name': 'overview',
                'verbose_name_plural': 'overviews',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='overview', verbose_name='image')),
            ],
            options={
                'verbose_name': 'structure',
                'verbose_name_plural': 'structures',
            },
        ),
        migrations.CreateModel(
            name='TerritorialDivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='region')),
                ('region_departament', models.CharField(blank=True, max_length=200, null=True, verbose_name='region_departament')),
                ('image', models.ImageField(upload_to='td', verbose_name='image')),
                ('phone_head', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_head')),
                ('phone_1deputy_head', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_1deputy_head')),
                ('phone_deputy_head', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone_deputy_head')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'territorialdivision',
                'verbose_name_plural': 'territorialdivisions',
            },
        ),
    ]
