# Generated by Django 3.2.12 on 2022-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_committee', '0003_auto_20220502_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoungPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
            ],
            options={
                'verbose_name': 'young_policy',
                'verbose_name_plural': 'young_policy',
            },
        ),
        migrations.AlterModelOptions(
            name='publiccouncil',
            options={'verbose_name': 'public_council', 'verbose_name_plural': 'public_councils'},
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='text1',
            field=models.TextField(verbose_name='text1'),
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='text2',
            field=models.TextField(verbose_name='text2'),
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='text3',
            field=models.TextField(verbose_name='text3'),
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='text4',
            field=models.TextField(verbose_name='text4'),
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='text5',
            field=models.TextField(verbose_name='text5'),
        ),
        migrations.AlterField(
            model_name='publiccouncil',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
