# Generated by Django 3.2.12 on 2022-05-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_committee', '0004_auto_20220502_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('rate', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_charge', models.CharField(blank=True, max_length=500, null=True)),
                ('qualification_requirements', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
